# Generated by Django 6.0.1 on 2026-01-30 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('race', models.CharField(choices=[('terran', 'Terran'), ('zerg', 'Zerg'), ('protoss', 'Protoss'), ('random', 'Random')], default='random', max_length=10)),
                ('macro', models.IntegerField(default=0)),
                ('micro', models.IntegerField(default=0)),
                ('multitasking', models.IntegerField(default=0)),
                ('strategy', models.IntegerField(default=0)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team')),
            ],
        ),
    ]
