# Generated by Django 4.1.4 on 2023-06-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(default='Country', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='Juan', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='Garcia', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='Stork', max_length=20),
            preserve_default=False,
        ),
    ]
