# Generated by Django 4.1.13 on 2026-01-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_player_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='macro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='micro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='multitasking',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='race',
            field=models.CharField(choices=[('terran', 'Terran'), ('zerg', 'Zerg'), ('protoss', 'Protoss'), ('random', 'Random')], default='random', max_length=10),
        ),
        migrations.AddField(
            model_name='player',
            name='strategy',
            field=models.IntegerField(default=0),
        ),
    ]
