# Generated by Django 6.0.1 on 2026-02-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_map_match_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='map',
        ),
        migrations.AddField(
            model_name='match',
            name='map_name',
            field=models.CharField(default='bloodbath', max_length=255),
        ),
        migrations.DeleteModel(
            name='Map',
        ),
    ]
